#! /bin/sh
#
# rc
#
# read/write brightness parameter on runlevel changea
#
# Authors:
#   Taihsiang Ho 
#

if  [ -e /etc/last_brightness ] ; then
        cat /etc/last_brightness > /sys/class/backlight/acpi_video0/brightness
else
        echo "called" > /etc/last_brightness_read_failed
fi

